# Generated by Django 4.0 on 2021-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('localization', models.CharField(max_length=120)),
                ('cat_id', models.IntegerField()),
                ('delivery', models.BooleanField(default=True)),
            ],
        ),
    ]
