# Generated by Django 4.0 on 2021-12-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
