# Generated by Django 4.0 on 2021-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0002_rename_meals_rest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='localization',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='rest',
            name='town',
            field=models.CharField(default='Jelenia Góra', max_length=120),
            preserve_default=False,
        ),
    ]
