# Generated by Django 4.0 on 2021-12-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0002_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rests.rest'),
        ),
        migrations.AlterField(
            model_name='rest',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rests.cat'),
        ),
    ]
