# Generated by Django 4.0 on 2021-12-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0003_rename_localization_rest_adress_rest_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='town',
        ),
    ]
