# Generated by Django 4.0 on 2021-12-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0004_remove_rest_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='price',
            field=models.IntegerField(),
        ),
    ]
