# Generated by Django 4.0 on 2021-12-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0004_rename_rest_id_meal_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
