# Generated by Django 4.0 on 2021-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rests', '0005_alter_rest_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='adress',
            new_name='town',
        ),
        migrations.AddField(
            model_name='rest',
            name='adres',
            field=models.CharField(default='Prosta 1/28', max_length=120),
        ),
    ]
